"""
Permission codes used throughout the application.
All authorization checks must use these codes.
"""

# Project permissions
PROJECT_CREATE = "PROJECT_CREATE"
PROJECT_VIEW_ALL = "PROJECT_VIEW_ALL"
PROJECT_VIEW_ASSIGNED = "PROJECT_VIEW_ASSIGNED"
PROJECT_EDIT = "PROJECT_EDIT"
PROJECT_DELETE = "PROJECT_DELETE"
PROJECT_CLOSE = "PROJECT_CLOSE"
PROJECT_APPROVE = "PROJECT_APPROVE"

# Task permissions
TASK_CREATE = "TASK_CREATE"
TASK_VIEW = "TASK_VIEW"
TASK_EDIT = "TASK_EDIT"
TASK_DELETE = "TASK_DELETE"
TASK_ASSIGN = "TASK_ASSIGN"
TASK_APPROVE = "TASK_APPROVE"

# User permissions
USER_CREATE = "USER_CREATE"
USER_VIEW = "USER_VIEW"          # basic view
USER_VIEW_ALL = "USER_VIEW_ALL"  # admin-only view all users
USER_EDIT = "USER_EDIT"
USER_DELETE = "USER_DELETE"
USER_ASSIGN_ROLE = "USER_ASSIGN_ROLE"
USER_MANAGE_ROLES = "USER_MANAGE_ROLES"

# Sprint permissions
SPRINT_CREATE = "SPRINT_CREATE"
SPRINT_VIEW = "SPRINT_VIEW"
SPRINT_EDIT = "SPRINT_EDIT"
SPRINT_DELETE = "SPRINT_DELETE"

# Time log permissions
TIME_LOG_CREATE = "TIME_LOG_CREATE"
TIME_LOG_VIEW = "TIME_LOG_VIEW"
TIME_LOG_EDIT = "TIME_LOG_EDIT"
TIME_LOG_DELETE = "TIME_LOG_DELETE"

# File permissions
FILE_UPLOAD = "FILE_UPLOAD"
FILE_VIEW = "FILE_VIEW"
FILE_DELETE = "FILE_DELETE"

# Billing permissions
BILLING_VIEW = "BILLING_VIEW"
BILLING_EDIT = "BILLING_EDIT"

# Dashboard permissions
DASHBOARD_VIEW = "DASHBOARD_VIEW"

